### ISSUE TITLE
[BUG]  Error: configmap "akv2k8s-ca" not found

### ISSUE THREAD

**Issue by sanjaypradeep** [SparebankenVest/azure-key-vault-to-kubernetes#180] opened 2021-06-02 07:43 UTC
Controller, version: spvest/azure-keyvault-controller:1.1.0
Env-Injector (webhook), version: spvest/azure-keyvault-webhook:1.1.10
Currently I'm in Azure AKS and the nodes are on K8S version v1.20.5

The akv2k8s-ca found missing. How to bring this back?

Reason for need?
1. Cannot able to deploy my docker image pods to ASK Cluster
2. Getting "CreateContainerConfigError" as status of pod.
3. when described the pod, showed   Error: configmap "akv2k8s-ca" not found

```
 Error: configmap "akv2k8s-ca" not found
```

**Comment by mcwienczek** [comment] 2021-06-03 08:34
I'm having the same issue. I recently updated cluster to 1.19. Could this be related?

**Comment by ammartins** [comment] 2021-06-03 08:47
Seems the issue is solved if you use app version  1.2.2 . (not Chart but the Image Tag for the app :) )
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/147

**Comment by mcwienczek** [comment] 2021-06-03 08:48
UPDATE: fixed by updating helm chart to 1.1.25 and all containers  to 1.2.2
see this issue for more info: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/147

**Comment by sanjaypradeep** [comment] 2021-06-03 12:42
hi @mcwienczek how did you upgraded the helm and containers? 

I use a jump vm to get  aks info. Much appreicated.

**Comment by mcwienczek** [comment] 2021-06-03 13:34
If you use official helm chart to deploy akv2k8s just upgrade your deployment with version `1.1.25` and also update your values.yaml and change all containers/pods version to `1.2.2`.

**Comment by lefkatis-hellenic** [comment] 2021-06-04 13:02
Hello
I just had the same issue. I updated 2 out of my 4 clusters from 1.19.9 to 1.19.11 and this issue occurred.

I am using 1.1.28 chart version and I have no values file. I am using the default values.
helm upgrade --namespace akv2k8s --install --wait akv2k8s spv-charts/akv2k8s --version 1.1.28

I will continue with the update of the remaining 2 clusters from 1.18.10 to 1.19.11

What versions should i use in order not to have this issue?
Should I downgrade in order to bypass this issue?
What chart version should I use?
Should I create a values file?

**Comment by mcwienczek-rtl** [comment] 2021-06-04 13:10
**UPDATE: we actually had to upgrade to helm chart version 2.0.10 to fix the problem.**

**Comment by mcwienczek** [comment] 2021-06-04 13:12
Update: we actually had to update helm chart to version 2.0.10. We did not change any containers after that. Looks like the ca-bundle controller is gone.

**Comment by lefkatis-hellenic** [comment] 2021-06-05 16:19
Thanks @mcwienczek 
Would 2.0.10 work with both AKS cluster versions 1.18.10 and 1.19.11?

**Comment by 181192** [comment] 2021-06-08 07:14
Hi @mcwienczek @lefkatis-hellenic @sanjaypradeep @ammartins 

Due to more aggressive garbage collector in k8s >= 1.18, we needed to change how the auth was working between the `azure-keyvault-env` and the env-injector webhook. So ca-bundle controller is not needed anymore. :relieved: 

It's recommended to upgrade to akv2k8s chart `>= 2.x.x` when using akv2k8s components `>= 1.2`, due to changes in default values and environment variables.
Due to breaking changes in the Helm chart a major version update was needed, and the old chart must be uninstalled first, rolling upgrade is not supported due to label selector changes etc..
Helm 3 does not handle CRD, so the CRD must be updated manual. 
If you did do a rolling update and pod restarts its failing, remember to check that there is only one `MutatingWebhookConfiguration`.

Latest [stable chart version 2.0.11](https://github.com/SparebankenVest/public-helm-charts/tree/akv2k8s-2.0.11/stable/akv2k8s)

**Closed by 181192** 2021-06-08 07:14 UTC
Labels: bug

**Comment by bgarcial** [comment] 2021-07-02 19:13
@lefkatis-hellenic Did you noticed the issue when you upgraded to `1.19.11` version? 
It means on Does it not presenting when your cluster had the  `1.19.9` version?

**Comment by dplunkett-straxintelligence** [comment] 2021-07-14 19:21
Just upgrades AKS nodes to 1.20.7 and all my pods are pending with the configmap "akv2k8s-ca" not found error.
I want to be sure of the fix because i'm still finding my way with k8.  Can anyone provide the steps/commands to uninstall my existing akv2k8s and install 2.0.11 helm charts for akv2k8s to resolve the issue. Thanks


  helm.sh/chart: akv2k8s-1.1.26
  name: akv2k8s-envinjector
  namespace: key-vault

  image: spvest/azure-keyvault-webhook:1.1.10

    - --version=1.1.10
    - --versionEnvIage=1.1.1
