### ISSUE TITLE
[Question] Dead project or what is going on

### ISSUE THREAD

**Issue by tskulbru** [SparebankenVest/azure-key-vault-to-kubernetes#740] opened 2024-09-11 08:39 UTC
This project hasnt seen updates in almost a year, and as far as I know the maintainers have left Sparebanken Vest and no longer has access to this repository. I have reached out to contacts in SPV to get someone to either continue maintenance or archive the repository but so far I havent heard anything back about any decisions.

I advice anyone that either uses this project, or think about using it to either 

1. fork it and do whatever you want with it
2. fork it for the general public and we can help contribute
3. steer clear and instead use something else, like hashicorp vault.

**Comment by andreasthuen** [comment] 2024-09-17 11:51
Hi @tskulbru! 
It is true that the maintenance and follow up on this project has been lacking since the original creators left the company.
However, we are still using this project ourselves and thus we are also dependent on it being maintained and updated at a regular interval. Therefore, we will be taking a more active role as owners and maintainers of this project going forward. 
Meaning that we will be dedicating time on a regular basis to develop, review and contribute to this project.

**Comment by Jaykul** [comment] 2024-09-18 18:54
Can you start by just doing an update to deal with the critical CVEs?

**Comment by andreasthuen** [comment] 2024-09-20 11:31
A new release has been released today `1.7.0`, helm-release `2.7.0`
This release fixes all known CVEs in the app, as well as adding support for multi arch deployment, allowing users to run in clusters running on ARM nodes.
Please let me know if you have any questions or comments 💬

**Comment by Sargastico** [comment] 2024-09-23 19:57
@andreasthuen 

I tried to use this new release to deploy akv2k8s on my arm64 nodes, but apparently the extracted image targets the wrong architecture and I got the following log from the pods:

`exec /usr/local/bin/azure-keyvault-controller: exec format error`

 I deployed it using helm, this is my `values.yaml`:
```
name: akv2k8s

controller:
  nodeSelector:
    beta.kubernetes.io/arch: arm64

env_injector:
  nodeSelector:
    beta.kubernetes.io/arch: arm64
```

I'm not sure if this is a bug in the image build pipeline or if it's a problem with my k8s setup (but I have other deployments that support multiple architectures running without problems) 🤔

**Comment by mozts2005** [comment] 2024-09-24 00:06
Looks as if only the arm64 images were published to docker hub. ![image](https://github.com/user-attachments/assets/8368f5a5-e9f4-44e9-a407-b557dcff8764)

**Comment by andreasthuen** [comment] 2024-09-24 05:45
Ok, we ourselves are not running any arm64 nodes, but I will spin some up and see if I am able to reproduce the issue.

**Comment by Jaykul** [comment] 2024-09-27 18:58
@andreasthuen perhaps I should open a fresh issue, but I don't think the multi arch publish worked.

![image](https://github.com/user-attachments/assets/bbf261c4-3454-415b-a48f-7a50bfb16ec8)

Akv2k8s has always published amd64 images, but this latest image seems to have **only** uploaded the arm64 images. There aren't two images with multi-arch metadata, as far as I can tell.

**Comment by andreasthuen** [comment] 2024-09-30 11:45
I have had a look at this issue now and it appears that the issue originated when I manually pushed the latest tag to dockerhub. Upon inspecting the image in our internal container registry it is correctly marked as `multiarch`. 
However, due to some issues with the pipeline I was not able make the release pipeline work as intended and publish to dockerhub. I did not think of that the manual push would result in an issue, but when reading a little more about multi-arch builds I see that it did. I will fix the pipeline and make a new patch release when the issue is resolved👍

**Comment by andreasthuen** [comment] 2024-09-30 13:15
I was able to successfully build and release for both `arm` and `x86`to dockerhub now. I will verify the `arm` build tomorrow.

**Comment by andreqz** [comment] 2024-10-03 11:57
How is the verification going? I'm trying to deploy this solution to arm architecture on Azure AKS and I have error like colleague above: 
exec /usr/local/bin/azure-keyvault-controller: exec format error

Thanks

**Comment by andreasthuen** [comment] 2024-10-03 18:21
I was able to reproduce the error. As far as I can see the root cause for this issue is that it is not sufficient to create a multiarch build using docker buildx, the GO binaries must also be built to support different architectures. I am planning to verify this theory tomorrow, and if I succeed I will start to adapt the makefile and pipeline to facilitate this setup. I will keep you guys posted on the progress 👍

**Closed** 2024-10-04 10:38 UTC
Labels: question
