### ISSUE TITLE
Injected env comes in as name@azurekeyvault instead of actual value

### ISSUE THREAD

**Issue by benrjnih** [SparebankenVest/azure-key-vault-to-kubernetes#1] opened 2019-05-31 21:40 UTC
I went through the installation steps detailed in the README, and all appeared to work fine, but when I go to grab the injected secret, the application sees it as `my-secret-ci-env@azurekeyvault` instead of the actual value from Azure Key Vault.  

What would this mean?

My yaml:
```
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: my-secret-ci-env
  namespace: default
spec:
  vault:
    name: my-dev-kv
    object:
      type: secret
      name: CI-ENV
```
and in my deployment:

```
        env:
        - name: CI_ENV
          value: my-secret-ci-env@azurekeyvault
```

And in my PHP application:
```
echo 'CI_ENV: ' . $_ENV['CI_ENV'];
```
Which displays: `CI_ENV: my-secret-ci-env@azurekeyvault`

Am I missing something?  Is there a place to find logs to see if the azure secret is being retrieved correctly?

**Comment by torresdal** [comment] 2019-05-31 21:50
Hi @benrjnih! Thanks for trying out the env-injector!

Logs: `kubectl -n <akv-ns> <akv-injector-pod-name>`

Take a look at those and post it here if you want us to have a look at it, and we'll try to help from there.

**Comment by torresdal** [comment] 2019-05-31 21:54
@benrjnih you can also desribe your pod (`kubectl -n <your-pod-ns> describe pod <pod-name>` and see if the env-injector correctly added a init-container to your pod.

**Comment by benrjnih** [comment] 2019-05-31 21:57
I wasn't able to get the first one running (is there a command missing?), but for the second, here's what I see:
```
$ kubectl -n default describe pod aks-test-web
Name:               aks-test-web-67b94bbfbd-k2jbf
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-34618682-0/10.240.0.5
Start Time:         Fri, 31 May 2019 16:22:49 -0400
Labels:             app=aks-test-web
                    pod-template-hash=67b94bbfbd
Annotations:        <none>
Status:             Running
IP:                 10.244.0.15
Controlled By:      ReplicaSet/aks-test-web-67b94bbfbd
Containers:
  aks-test-web:
    Container ID:   docker://618cc67e4afa14c8a1c55995ae2fe28313523c66a1ab9a75dc7911f4a3ac1a02
    Image:          acr1.azurecr.io/aks-test-web:v5
    Image ID:       docker-pullable://acr1.azurecr.io/aks-test-web@sha256:db866a9c8522e0175dc748ebc7992b2c51e9948ec474df9930370a80cb217135
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 31 May 2019 16:22:52 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:  500m
    Requests:
      cpu:  250m
    Environment:
      CI_ENV:                        my-secret-ci-env@azurekeyvault
      KUBERNETES_PORT_443_TCP_ADDR:  epmap-aks1-epmap-dev-rg1-87e639-45711b21.hcp.eastus.azmk8s.io
      KUBERNETES_PORT:               tcp://epmap-aks1-epmap-dev-rg1-87e639-45711b21.hcp.eastus.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://epmap-aks1-epmap-dev-rg1-87e639-45711b21.hcp.eastus.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       epmap-aks1-epmap-dev-rg1-87e639-45711b21.hcp.eastus.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sxttw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-sxttw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sxttw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```

**Comment by torresdal** [comment] 2019-05-31 22:00
There is no init-container running there, so something is not right. Have you installed env-injector using Helm? Can you find the name of the env-injector pod? `kubectl get pods --all-namespaces` should give you all pods in the entire cluster.

**Comment by benrjnih** [comment] 2019-05-31 22:08
@torresdal - thanks for your prompt help!

Yes, I installed it using Helm:
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                              READY   STATUS    RESTARTS   AGE
default       aks-test-web-67b94bbfbd-k2jbf                                     1/1     Running   0          105m
default       gauche-chinchilla-azure-key-vault-env-injector-8666b6bf87-mj89p   1/1     Running   0          152m
default       goodly-moth-azure-key-vault-controller-85b54ff4c8-rbcfw           1/1     Running   0          39m
```

**Comment by torresdal** [comment] 2019-05-31 22:11
You should get the logs by running:

```
kubectl -n default logs gauche-chinchilla-azure-key-vault-env-injector-8666b6bf87-mj89p
```

**Comment by benrjnih** [comment] 2019-05-31 22:12
```
$ kubectl -n default logs gauche-chinchilla-azure-key-vault-env-injector-8666b6bf87-mj89p
initializing config...
config initialized
2019/05/31 19:35:56 [WARN] no metrics recorder active
2019/05/31 19:35:56 [WARN] no tracer active
2019/05/31 19:35:56 [INFO] listening on :443
```

**Comment by torresdal** [comment] 2019-05-31 22:16
...but I just realized someting. For the env-injector you specifically need to enable it per namespace as describe here: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/README.md#env-injector (I see now that we need to mention this in the install section as well).

**Comment by torresdal** [comment] 2019-05-31 22:25
We also recommend using separate namespaces for pods you're going to inject into, and especially not have the env-injector and your pods in the same namespace. We'll update the docs with an explanation of why (this is currently a bit problematic with mutating web hooks in Kubernetes, which we are using for this).

**Comment by torresdal** [comment] 2019-05-31 22:26
Hopefully this solves your problem. Let us know how it goes. Thanks.

**Comment by benrjnih** [comment] 2019-05-31 22:32
Ahh.. thank you, that looks like it helped, but it looks like I'm on to an authentication issue now:
```
$ kubectl -n default logs gauche-chinchilla-azure-key-vault-env-injector-8666b6bf87-mj89p
initializing config...
config initialized
2019/05/31 19:35:56 [WARN] no metrics recorder active
2019/05/31 19:35:56 [WARN] no tracer active
2019/05/31 19:35:56 [INFO] listening on :443
time="2019-05-31T22:28:11Z" level=info msg="found pod to mutate in namespace 'akv-injection'"
2019/05/31 22:28:12 [ERROR] admission webhook error: secrets "aks-acr-auth-g95999d5d6" not found
```

I'll dig into that further, but I'm wondering if it is something to do with authentication.  that auth is our imagePullSecret, but I'm not sure why it's being used here?

**Comment by torresdal** [comment] 2019-05-31 22:38
The env-injector needs to download the image to read its metadata (run path). If the pod has specified a pull secret, it will try to use that for downloading the image. It's been a while since we used pull secrets for this our selves, so you might have run into an issue we're unaware of. If that's the case, would you mind closing this issue and open a new one for that? We'll help you as quickly as we can.

**Comment by torresdal** [comment] 2019-05-31 22:49
Fore reference, here's a successful log output:

```
time="2019-05-29T06:28:35Z" level=info msg="found pod to mutate in namespace 'xxx'"
time="2019-05-29T06:28:35Z" level=info msg="found container 'yyy' to mutate"
time="2019-05-29T06:28:35Z" level=info msg="checking for env vars containing '@azurekeyvault' in container yyy"
time="2019-05-29T06:28:35Z" level=info msg="found env var: zzz@azurekeyvault"
time="2019-05-29T06:28:35Z" level=info msg="did not find credentials to use with registry 'dokken.azurecr.io' - getting default credentials"
time="2019-05-29T06:28:35Z" level=info msg="using default credentials for docker registry with clientid: xxx-xxx-xxx-xxx-xxx"
time="2019-05-29T06:28:35Z" level=info msg="pulling docker image a.azurecr.io/yyy:test-de5d244cc7a4f9c61e0be50fffb65d53b54e350e to get entrypoint and cmd, timeout is 30 seconds"
time="2019-05-29T06:28:36Z" level=info msg="docker image a.azurecr.io/yyy:test-de5d244cc7a4f9c61e0be50fffb65d53b54e350e pulled successfully"
time="2019-05-29T06:28:36Z" level=info msg="inspecting container image a.azurecr.io/yyy:test-de5d244cc7a4f9c61e0be50fffb65d53b54e350e, looking for entrypoint and cmd"
time="2019-05-29T06:28:36Z" level=info msg="found entrypoint: [dotnet Api.dll]"
time="2019-05-29T06:28:36Z" level=info msg="using 'dotnet Api.dll' as arguments for env-injector"
time="2019-05-29T06:28:36Z" level=info msg="containers mutated and pod updated with init-container and volumes"
```

**Comment by benrjnih** [comment] 2019-06-03 15:51
Thanks for your help on this @torresdal !

I was able to get this working - I removed the `imagePullSecret`, which we ended up not needing.

I had a few issues with the container failing because it [couldn't find the secret](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/cmd/azure-keyvault-env/main.go#L135).  I found that changing the namespace of the secret itself to match the namespace I'm using to enable env injection was required.  It might be good to update the documentation to call that out (particularly since [the examples](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes#the-env-injector) have the `AzureKeyVaultSecret`s in the `default` namespace.

Also, I wonder if it might be advisable not to consider the failure to retrieve a secret a fatal error (either [here](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/cmd/azure-keyvault-env/main.go#L135), [here](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/cmd/azure-keyvault-env/main.go#L141) or [here](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/cmd/azure-keyvault-env/main.go#L145)), as it appears that prevents the container from starting.  Perhaps it should just be logged and then allow the application to handle a missing environment variable?

**Comment by torresdal** [comment] 2019-06-07 06:39
Good to hear you got it working and thanks for your feedback @benrjnih. We will definitely look at your suggestions and update the docs (pull requests welcome too 😊). Will re-test imagePullSecret to make sure everything is working as intended.

**Closed** 2019-06-20 19:49 UTC

**Comment by hisuwh** [comment] 2019-07-12 10:06
I'm experiencing the same problem as the OP.  I have tried what I believe to be the suggestions here (though it is a little unclear and it seems the docs haven't been updated yet)
 - put the injector, and secrets in a separate namespace - is this correct?

I'm getting the same initial logs from the injector as the OP.

I'm getting the following logs from the controller: 

```

time="2019-07-12T10:02:21Z" level=error msg="error syncing 'keyvault/test-config-value': failed to get secret from Azure Key Vault for secret 'keyvault'/'test-config-value', error: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Forbidden\" Message=\"Access denied\" InnerError={\"code\":\"AccessDenied\"}, requeuing"
time="2019-07-12T10:02:21Z" level=error msg="error syncing 'keyvault/test-config-value': failed to get secret from Azure Key Vault for secret 'keyvault'/'test-config-value', error: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Forbidden\" Message=\"Access denied\" InnerError={\"code\":\"AccessDenied\"}, requeuing"
time="2019-07-12T10:02:22Z" level=error msg="error syncing 'keyvault/test-config-value': failed to get secret from Azure Key Vault for secret 'keyvault'/'test-config-value', error: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"Forbidden\" Message=\"Access denied\" Inne
```

**Comment by hisuwh** [comment] 2019-07-12 10:15
I've fixed the controller issues.  I need to add an access policy against the keyvault instance in azure to allow the AKS instance to read the secrets.  Probably worth adding this to the readme.

Got these logs from the controller now:

```
time="2019-07-12T10:11:22Z" level=info msg="Log level set to 'info'"
time="2019-07-12T10:11:22Z" level=info msg="Creating event broadcaster"
time="2019-07-12T10:11:22Z" level=info msg="Setting up event handlers"
time="2019-07-12T10:11:22Z" level=info msg="Starting AzureKeyVaultSecret controller"
time="2019-07-12T10:11:22Z" level=info msg="Waiting for informer caches to sync"
time="2019-07-12T10:11:22Z" level=info msg="Starting workers"
time="2019-07-12T10:11:22Z" level=info msg="Started workers"
time="2019-07-12T10:11:23Z" level=info msg="Updating status for AzureKeyVaultSecret 'test-config-value'"
time="2019-07-12T10:11:23Z" level=info msg="Successfully synced AzureKeyVaultSecret 'keyvault/test-config-value' with Kubernetes Secret"
time="2019-07-12T10:11:23Z" level=info msg="Successfully synced AzureKeyVaultSecret 'keyvault/test-config-value' with Kubernetes Secret"
time="2019-07-12T10:11:23Z" level=info msg="Successfully synced AzureKeyVaultSecret 'keyvault/test-config-value' with Kubernetes Secret"
```

Still only getting these logs from the injector:
```
2019/07/12 10:11:24 [WARN] no metrics recorder active
2019/07/12 10:11:24 [WARN] no tracer active
2019/07/12 10:11:24 [INFO] listening on :443
initializing config...
config initialized
```

**Comment by hisuwh** [comment] 2019-07-12 12:43
I've fixed this now. I have:
 - deployed the injector and controller and secret defintions to a seperate namespace
 - enabled the injector for this namespace
 - enabled the injector for the default namespace
 - deployed a new image to the container which seemed to trigger the mutate

I'm getting these logs from the injector now:
```
time="2019-07-12T11:26:18Z" level=info msg="found pod to mutate in namespace 'default'"
time="2019-07-12T11:26:18Z" level=info msg="found container 'company-serviceapi' to mutate"
time="2019-07-12T11:26:18Z" level=info msg="checking for env vars containing '@azurekeyvault' in container company-serviceapi"
time="2019-07-12T11:26:18Z" level=info msg="found env var: test-config-value@azurekeyvault"
time="2019-07-12T11:26:18Z" level=info msg="found credentials to use with registry 'ebcsharedcontaineregistryeun.azurecr.io'"
time="2019-07-12T11:26:18Z" level=info msg="pulling docker image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902 to get entrypoint and cmd, timeout is 30 seconds"
time="2019-07-12T11:26:28Z" level=info msg="docker image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902 pulled successfully"
time="2019-07-12T11:26:28Z" level=info msg="inspecting container image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902, looking for entrypoint and cmd"
time="2019-07-12T11:26:28Z" level=info msg="found entrypoint: [dotnet company.product.Api.dll]"
time="2019-07-12T11:26:28Z" level=info msg="using 'dotnet company.product.Api.dll' as arguments for env-injector"
time="2019-07-12T11:26:28Z" level=info msg="containers mutated and pod updated with init-container and volumes"
time="2019-07-12T11:26:28Z" level=info msg="found pod to mutate in namespace 'default'"
time="2019-07-12T11:26:28Z" level=info msg="found container 'company-serviceapi' to mutate"
time="2019-07-12T11:26:28Z" level=info msg="checking for env vars containing '@azurekeyvault' in container company-serviceapi"
time="2019-07-12T11:26:28Z" level=info msg="found env var: test-config-value@azurekeyvault"
time="2019-07-12T11:26:28Z" level=info msg="found credentials to use with registry 'ebcsharedcontaineregistryeun.azurecr.io'"
time="2019-07-12T11:26:28Z" level=info msg="pulling docker image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902 to get entrypoint and cmd, timeout is 30 seconds"
time="2019-07-12T11:26:28Z" level=info msg="docker image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902 pulled successfully"
time="2019-07-12T11:26:28Z" level=info msg="inspecting container image ebcsharedcontaineregistryeun.azurecr.io/company-serviceapi:24902, looking for entrypoint and cmd"
time="2019-07-12T11:26:28Z" level=info msg="found entrypoint: [dotnet company.product.Api.dll]"
time="2019-07-12T11:26:28Z" level=info msg="using 'dotnet company.product.Api.dll' as arguments for env-injector"
time="2019-07-12T11:26:28Z" level=info msg="containers mutated and pod updated with init-container and volumes"
```

Which looks good.  But I'm getting this error from my pod:
```
level=fatal msg="env-injector: error getting azurekeyvaultsecret resource 'test-config-value', error: azurekeyvaultsecrets.spv.no \"test-config-value\" not found"
```

**Comment by hisuwh** [comment] 2019-07-12 12:55
I have got it working now. Sorry for the noise but for the sake of anyone else looking at this, these are the full list of steps I had to go through to get this working correctly:
 - deployed the injector and controller to a seperate namespace
 - specify secret defintions in the same namespace as your pod
 - enabled the injector for this namespace
 - enabled the injector for the default namespace
 - deployed a new image to the container which seemed to trigger the mutate

I'll try and send a pr on your readme to clarify this.
