### ISSUE TITLE
azureKeyVaultResourceURI should be configurable

### ISSUE THREAD

**Issue by yarinm** [SparebankenVest/azure-key-vault-to-kubernetes#12] opened 2019-07-31 06:30 UTC
It seems that this constant [is not configurable](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/pkg/azurekeyvault/client/authentication.go#L15) 

On some azure instances (private cloud ones, like FairFax, MoonCake etc.), the azure keyvault resource URI is different from value defined, see this [link](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide) for me details

We need the ability to configure the controller to run with a different value. 

I'll try and create a PR about it the next few days. This issue is to keep track of it.

**Comment by torresdal** [comment] 2019-08-12 08:34
Hi @yarinm,

Agree this should be configurable. Any pull-request, or should we look at it?

**Comment by yarinm** [comment] 2019-08-12 11:29
Hey @torresdal I was evaluating the project and I don't think we'll use it. The main drawback here is that if we're using MSI and aad-pod-identity we're restricted to using one identity to access all of our kubernetes secrets which is something we don't wish to do.

So I'm afraid I won't be doing that anytime soon :)

**Comment by dmitriysklyarov** [comment] 2019-08-21 19:36
I have faced an issue with lack of URI using this project for Azure China where KeyVault instance domain ends with **azure.cn** whilst current implementation looks to be hardcoded to send requests to **azure.net**

**Comment by torresdal** [comment] 2019-08-23 09:59
@dmitriysklyarov We'll add an option of configuring endpoints. Please feel free to provide a pull-request if you want to fast-track this.

**Comment by torresdal** [comment] 2020-02-28 17:08
Duplicate of #28 - will follow up there.

**Closed by torresdal** 2020-02-28 17:08 UTC
Labels: enhancement
