### ISSUE TITLE
[BUG] Cleaning up controller using terraform doesn't remove the CRD

### ISSUE THREAD

**Issue by nadworny** [SparebankenVest/azure-key-vault-to-kubernetes#51] opened 2020-03-25 09:43 UTC
**Describe the bug**
We're using terraform to setup our AKS which also installs the akv2k8s using helm provider. Upon terraform destroy the following error appears:
`Error: uninstallation completed with 1 error(s): uninstall: Failed to purge the release: delete: failed to get release "sh.helm.release.v1.azure-key-vault-controller.v1": release: not found`

After trying to apply the terraform plan after that the following error will be thrown:
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: azurekeyvaultsecrets.spv.no, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apie
xtensions.k8s.io/v1beta1, Kind=CustomResourceDefinition`

**To Reproduce**
Setup AKS cluster (i.e. using this quickstart https://github.com/Azure/terraform/tree/master/quickstart/201-aks-helm) and add the following to install helm chart
```
provider "kubernetes" {
  host = data.azurerm_kubernetes_cluster.default.kube_config.0.host

  client_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_certificate)
  client_key = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)
}

provider "helm" {
  kubernetes {
    host = data.azurerm_kubernetes_cluster.default.kube_config.0.host

    client_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_certificate)
    client_key = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)
  }
}

data "helm_repository" "spv" {
  name = "spv"
  url = "http://charts.spvapi.no"
}

resource "kubernetes_namespace" "default" {
  metadata {
    name = local.aks_namespace
  }
}

resource "helm_release" "azure_keyvault_controller" {
  name = "azure-key-vault-controller"
  repository = data.helm_repository.spv.metadata[0].name
  chart = "azure-key-vault-controller"
  namespace = local.aks_namespace
}
```

**Expected behavior**
CRD should be cleaned up properly.
After executing manually the `kubectl delete -f .\crd.yaml` I can perform `terraform apply` successfully.

**Comment by torresdal** [comment] 2020-03-25 13:20
The short answer is we can’t. As long as we support Helm 2, there is no safe way of removing crd’s. Helm 3 is better and covered here: sparebankenvest/public-helm-charts#18. But we still need to support Helm 2 for some time still. As for using the TF helm provider I know @vidarw has some insight he might want to share?

**Comment by nadworny** [comment] 2020-03-25 15:43
Thanks for a super quick reply!

I'm a bit confused as I'm using the latest 1.1.0 version of terraform helm provider meaning it should use helm3 for the deployment.

**Comment by torresdal** [comment] 2020-03-25 20:52
Using Helm 3 is fine, because it’s backwards compatible with Helm 2. To be 100% accurate, Helm 2 is using the Helm v1 schema and Helm 3 the v2 schema. Helm 2 only support v1, Helm 3 support both v1 and v2. In this case it’s the v1 schema that blocks us from using the new crd stuff. 

If we upgrade our current v1 schema to v2, Helm 2 will no longer work with akv2k8s. This is something we will do soon, but Helm 3 adoption is still a bit slow. As you know, the TF helm provider only very recently added support for Helm 3.  

What we will do as soon as we get v 1.1.0 of akv2k8s out the door, is to finish the implementation of the v2 schema started here: https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/akv2k8s (feel free to contribute 😊)

**Comment by torresdal** [comment] 2020-03-26 06:19
Duplicate of sparebankenvest/public-helm-charts#18. Closing.

**Closed by torresdal** 2020-03-26 06:19 UTC
Labels: bug
